/**
 * Mana Pool affiliate links.
 * --------------------------------------------------------------------------
 * Buy links point at manapool.com with our referral code. Attribution is
 * first-click within a 7-day window (tracked by Mana Pool via TapFiliate), so
 * the ref just needs to be present in the outgoing URL. The code isn't secret
 * (it's in the URL), so NEXT_PUBLIC_ is intentional and lets server + client
 * build links. TCGplayer is still our *price* source (via Scryfall), but no
 * longer a buy destination.
 */
const REF = process.env.NEXT_PUBLIC_MANAPOOL_REF ?? "budgetdecks";

function withRef(base: string): string {
  const u = new URL(base);
  u.searchParams.set("ref", REF);
  return u.toString();
}

/** Card-name → Mana Pool card-page slug (e.g. "Cruel Celebrant" → "cruel-celebrant"). */
export function cardSlug(name: string): string {
  return name
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "") // strip diacritics
    .toLowerCase()
    .replace(/æ/g, "ae")
    .replace(/œ/g, "oe")
    .replace(/['’.]/g, "") // drop apostrophes / periods
    .replace(/[^a-z0-9]+/g, "-") // everything else → hyphen
    .replace(/^-+|-+$/g, "");
}

export interface BuyCard {
  name: string;
  quantity: number;
}

/** Single-card buy link → Mana Pool card page. */
export function manapoolCardUrl(name: string): string {
  return withRef(`https://manapool.com/card/${cardSlug(name)}`);
}

/** Mana Pool Mass Entry page (the deck `deck=` token is generated by their tool,
 * so we open the paste page with our ref and supply the list via the clipboard). */
export function manapoolDeckUrl(): string {
  return withRef("https://manapool.com/add-deck");
}

/** Mana Pool home (used for the affiliate badge). */
export function manapoolHomeUrl(): string {
  return withRef("https://manapool.com/");
}

/** "1 Sol Ring\n1 Llanowar Elves" — for pasting into Mass Entry. */
export function deckListText(cards: BuyCard[]): string {
  return cards.map((c) => `${c.quantity} ${c.name}`).join("\n");
}
