/** Common EDHREC-style deck themes/archetypes. Decks may tag up to 3. */
export const ARCHETYPES = [
  "Aggro",
  "Aristocrats",
  "Artifacts",
  "Auras",
  "Blink",
  "Burn",
  "Cantrips",
  "Combo",
  "Control",
  "Curses",
  "Cycling",
  "Devotion",
  "Discard",
  "Enchantress",
  "Energy",
  "Equipment",
  "Extra Turns",
  "Goad",
  "Graveyard",
  "Group Hug",
  "Hatebears",
  "Infect",
  "Landfall",
  "Lands",
  "Lifegain",
  "Mill",
  "Monarch",
  "Pillow Fort",
  "Planeswalkers",
  "Politics",
  "Ramp",
  "Reanimator",
  "Sacrifice",
  "Spellslinger",
  "Stax",
  "Storm",
  "Theft",
  "Tokens",
  "Treasure",
  "Tribal",
  "Vehicles",
  "Voltron",
  "Wheels",
  "+1/+1 Counters",
  "-1/-1 Counters",
] as const;

export type Archetype = (typeof ARCHETYPES)[number];
export const ARCHETYPE_SET: ReadonlySet<string> = new Set(ARCHETYPES);
export const MAX_ARCHETYPES = 3;
